initContainers: 
   - name: velero-plugin-for-aws
     image: velero/velero-plugin-for-aws:v1.0.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins
configuration:
  provider: aws
  backupStorageLocation:
    name: aws
    bucket: velero
    config:
      region: minio
      s3ForcePathStyle: true
      publicUrl: http://localhost:30900
      s3Url: http://my-minio.default.svc:9000
  volumeSnapshotLocation:
    name: aws
    config: 
      region: minio

credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = minio
      aws_secret_access_key = minio123
snapshotsEnabled: false
